itws/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
	url(r'^sensor/',include('sensor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'^login/',views.loginpage,name="login-page"),
]

sensor/urls.py
from django.conf.urls import url
from . import views
from .views import *
app_name = 'sensor'
urlpatterns = [
    # ex: /polls/
    url(r'^(?P<pid>[0-9]+)$', views.index, name='index'),url(r'^m$',views.getdata,name="getdata"),   
    url(r'^gen/$', views.gen, name='gen'),
    #Register url
    url(r'^register/$',views.register,name="register"),
    url(r'^add/$',views.addPlant,name='addPlant'),
    url(r'^mod/$',views.modPlant,name='modPlant'),
    #Login url
    url(r'^login_user/$', views.login_user, name='login_user'),
    #Logout url
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pid>[0-9]+)/home/$', views.home, name='main-home'),
    #temperature for graph
    url(r'^(?P<pid>[0-9]+)/temp/$', HomeView.as_view(), name='home'),
    url(r'^(?P<pid>[0-9]+)/api/chart/data/$', ChartData.as_view(),name="api-da"),
    #Humidity for graph
    url(r'^(?P<pid>[0-9]+)/humid/$', HumidView.as_view(), name='home-humid'),
    url(r'^(?P<pid>[0-9]+)/api/chart1/data/$', ChartHumidData.as_view(),name="api-humid-da"),

    #Moisture for graph
    url(r'^(?P<pid>[0-9]+)/moist/$', MoistView.as_view(), name='home-moist'),
    url(r'^(?P<pid>[0-9]+)/api/chart2/data/$', ChartMoistData.as_view(),name="api-moist-da"),


    #sending data to the index.html
    url(r'^api/data/$', get_data, name='api-data'),


]

sensor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime 
from django.contrib.auth.models import Permission, User
#Plant class
#This class identifies each plant. A user can have multiple plants
#Life value decides if water is needed to be added to plant
#Life value of 0 represents moisture value 0 which means plant
#immediately needs to be watered. Otherwise it is 1.
class Plant(models.Model):
	user=models.ForeignKey(User,default=1)
	plant_type=models.CharField(max_length=20)
	latitude=models.FloatField(default=13.562975)
	longitude=models.FloatField(default=80.021457)
	life=models.IntegerField(default=1)
	def __str__(self):
        	return self.plant_type
	
#Temperature class
#This class stores the temperature (0c)for each of the plants
#along with the time when it was taken
class Temperature(models.Model):
    temperature = models.CharField(max_length=20)
    time=models.CharField(max_length=50)
    pid = models.ForeignKey(Plant, on_delete=models.CASCADE)
    def __str__(self):
        return self.temperature


#Humidity class
#This class stores humidity value in % (relative humidity)
#along with the time when it was taken
class Humidity(models.Model):
	humidity = models.CharField(max_length=20)
	time = models.CharField(max_length=50)
	pid = models.ForeignKey(Plant, on_delete=models.CASCADE)
	def __str__(self):
        	return self.humidity

#Soil pH class
#This class stores pH value for each plant.
#along with the time when it was taken. Since the plants may be widely 
#separated, we have assumed that pH can change for each of the plants
class soilPH(models.Model):
	pH = models.CharField(max_length=30)
	date = models.CharField(max_length=20)
	pid = models.ForeignKey(Plant, on_delete=models.CASCADE)
	def __str__(self):
        	return self.pH
#soil Moisture
#It stores the soil moisture value in % corresponding to each of the plants
#along with the time when it was taken
class soilMoisture(models.Model):
	moisture = models.CharField(max_length=20)
	time = models.CharField(max_length=20)
	pid = models.ForeignKey(Plant, on_delete=models.CASCADE)
	def __str__(self):
        	return self.moisture
#This class stores the water level of the tank
#along with the time when it was taken
class Depth(models.Model):
	depth = models.CharField(max_length=20)
	time = models.CharField(max_length=20)
	def __str__(self):
		return self.depth
#This class stores the Rain Gauge value(in cm)
#along with the time when it was taken
class Rain(models.Model):
	rainfall = models.CharField(max_length=20)
	time = models.CharField(max_length=20)
	def __str__(self):
		return self.rainfall

sensor/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Plant
class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	email=forms.EmailField(label='Email')
	class Meta:
		model=User
		fields=['username','email','password']
class LoginForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=['username','password']
class AddPlant(forms.ModelForm):
	plant_type=forms.CharField(label='Plant type')
	latitude=forms.FloatField(label='Latitude')
	longitude=forms.FloatField(label='Longitude')

	class Meta:
		model=Plant
		fields=['plant_type']

class ModPlant(forms.ModelForm):
	pid=forms.CharField(label='Plant id')
	latitude=forms.FloatField(label='Latitude')
	longitude=forms.FloatField(label='Longitude')

	class Meta:
		model=Plant
		fields=['pid','latitude','longitude']

itws/views.py
from __future__ import unicode_literals
import time
from django.shortcuts import get_object_or_404, render,redirect
from django.template import loader
from django.http import HttpResponse

from django.http import Http404
#from sensor.models import *

def index(request):
    #return render(request, 'sensor/itws.html')
    return render(request,'sensor/main_index.html')
def loginpage(request):
	return render(request,'sensor/base.html')

sensor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import time
from django.shortcuts import get_object_or_404, render,redirect
from django.template import loader
from django.http import HttpResponse
from .models import *
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt

#from django.views.generic.edit import CreateView,UpdateView,DeleteView
#from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate,login,logout
#from django.views import generic
#from django.views.generic import View
from .forms import UserForm
from .forms import LoginForm,AddPlant
from .forms import *
#--------------------------
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response
import time
#--------------------------------
#View to show temperature,humidity,etc. on the webpage
#location = [latitude longitude pid message ]
location = []
@login_required(login_url='/sensor/login_user/')
def index(request,pid):
    users=User.objects.all()
    plant=Plant.objects.filter(pk=pid)
    r=0
    for user in users:
	if(plant[0].user==user):
		if(request.user==user):
			r=1
    if(r):
	    temp = Temperature.objects.filter(pid=pid)
	    humid = Humidity.objects.filter(pid=pid)
	    if len(temp) > 0:
		s=temp[len(temp)-1]
		op1=int(s.temperature)
	    else:
		op1 = "NaN"
	    if len(humid) > 0:
		w=humid[len(humid)-1]
		op2=int(w.humidity)
	    else:
		op2 = "NaN"
	    depth = Depth.objects.all()
	    if len(depth) > 0:
		p=depth[len(depth)-1]
		op3=int(p.depth)
	    else:
		op3 = "NaN"
	    dept = soilMoisture.objects.filter(pid=pid)
	    if len(dept) > 0:
		p=dept[len(dept)-1]
		op4=int(p.moisture)
	    else:
		op4 = "NaN"
	    rain=Rain.objects.all()
	    if len(rain) > 0:
		w=rain[len(rain)-1]
		op6=int(w.rainfall)
	    else:
		op6 = "NaN"
	    plants=Plant.objects.all()
	    for i in plants:
		if(i.id==int(pid)):
			uid=i.user.id
			break
	    plants=Plant.objects.filter(user=uid)
	    pid=str(pid)
	    context = {'temp': op1,'humid':op2, 'depth':op3, 'moist':op4,'pid':pid,'user':uid,'plants':plants,'rain':op6}
	    return render(request, 'sensor/index.html', context)
    else:
	raise Http404("Sorry...You don't have this plant" );   
#Checks if no. of records is greater than 150 and if true deletes 50 oldest records
'''def check():
    temp = Temperature.objects.all()
    humid = Humidity.objects.all()
    depth = Depth.objects.all()
    dept = soilMoisture.objects.all()
    if(len(temp)>150):
        for i in range(0,51):
            a=temp[i]
            a.delete()
    if(len(humid)>150):
        for i in range(0,51):
            a=humid[i]
            a.delete()
    if(len(depth)>150):
        for i in range(0,51):
            a=depth[i]
            a.delete()
    if(len(dept)>150):
        for i in range(0,51):
            a=dept[i]
            a.delete()
'''
#It acts as a pseudo view which works with pseudo url .../sensor/m?t=''&h=''&...  Helps in storing data in database.
#
@csrf_exempt
def getdata(request):
    temp=request.GET['t']
    humid=request.GET['h']
    dept=request.GET['d']
    mois = request.GET['mo']
    pi=request.GET['pid']
    rain=request.GET['rain']
    d=time.ctime()
    plant=Plant.objects.filter(id=int(pi))
    latitude = plant[0].latitude
    longitude = plant[0].longitude
    message = 'Plant '+str(pi)
    flag=0
    for i in range(0,len(location)):
        if location[i][3] == int(pi):
            location[i][0] = message
            location[i][1] = latitude
            location[i][2] = longitude
            flag=1
    if flag == 0:
        location.append([message,latitude,longitude,int(pi)])
    f=Temperature(temperature=temp,time=d,pid=plant[0])
    f.save()
    s = Depth(depth=dept,time=d)
    s.save()
    q=Humidity(humidity=humid,time=d,pid=plant[0])
    q.save()
    m=soilMoisture(moisture=mois,time=d,pid=plant[0])
    if(m<=0):
       plant[0].life=0
    plant[0].save()
    m.save()
    s=Rain(rainfall=rain,time=d)
    s.save()
    #check()
    return HttpResponse(str(temp))
#Logout view logouts the user and redirects the user to login page.
def logout_user(request):
    logout(request)
    #form = LoginForm(request.POST or None)
    #context = {
     #   "form": form,
    #}
    #return render(request, 'sensor/login.html', context)
    return render(request,'sensor/main_index.html/')

def plant_location(plants,locate):
	#a=[]
	for p in plants:
		a=[]
		a.append(p.latitude)
		a.append(p.longitude)
		a.append(p.id)
		moist = soilMoisture.objects.filter(pid=p.id)
		if len(moist)>0:
			mo = moist[len(moist)-1]
		else:
			mo = "NaN"
		humid = Humidity.objects.filter(pid=p.id)
		if len(humid)>0:
			h = humid[len(humid)-1]
		else:
			h = "NaN"
		temp = Temperature.objects.filter(pid=p.id)
		if len(temp)>0:
			t = temp[len(temp)-1]
		else:
			t = "NaN"
		s=p.plant_type
		a.append(str("Plant "+str(p.id)+" "+str(s)+"\n"+"Moisture: "+str(mo)+" %\n"+"Temperature: "+str(t)+" C\nHumidity: "+str(h)+" %"))
		locate.append(a)
	print(locate)
	return locate
#View to allow users to register on our Website.
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
		plants = Plant.objects.filter(user=request.user)
		for p in plants:
			d=soilMoisture.objects.filter(pid=p)
			if(len(d)>0):
				d=int(d[len(d)-1].moisture)
			else:
				d=1
			if(d!=0):
				d=1
			p.life=d
			p.save()
		plants = Plant.objects.filter(user=request.user)
                #albums = Album.objects.filter(user=request.user)
                locate=[]
                locate=plant_location(plants,locate)
                return render(request, 'sensor/itws.html',{'username':username,'plants':plants,'mapdata':locate})
    context = {
        "form": form,
    }
    return render(request, 'sensor/signup.html', context)
#This view allows users to login. It gets called when url ~/sensor/login_user is called
#Takes username and password from user and authenticates the user.
def login_user(request):
    form = LoginForm(request.POST or None)
    context = {
        "form": form,
    }
    context2={
    	"form":form,
    	'error_message':'Invalid Credentials'
    }
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                plants = Plant.objects.filter(user=request.user)
		for p in plants:
			d=soilMoisture.objects.filter(pid=p)
			if(len(d)>0):
				d=int(d[len(d)-1].moisture)
			else:
				d=1
			if(d!=0):
				d=1
			p.life=d
			p.save()
		plants = Plant.objects.filter(user=request.user)
                #return render(request, 'sensor/itws.html', {'albums': albums})
                locate=[]
                locate=plant_location(plants,locate)
                return render(request,'sensor/itws.html',{'username':username,'plants':plants,'mapdata':locate})
            else:
                return render(request, 'sensor/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'sensor/login.html', context2)
    return render(request, 'sensor/login.html',context)

@login_required(login_url='/sensor/login_user/')
def addPlant(request):
    form = AddPlant(request.POST or None)
    if request.method=="POST":
        user = request.user
        plant_type = request.POST['plant_type']
	latitude = request.POST['latitude']
	longitude = request.POST['longitude']
        plant=Plant(user=user,plant_type=plant_type,latitude=latitude,longitude=longitude,life=1)
	plant.save()
        plants = Plant.objects.filter(user=user)
	for p in plants:
		d=soilMoisture.objects.filter(pid=p)
		if(len(d)>0):
			d=int(d[len(d)-1].moisture)
		else:
			d=1
		if(d!=0):
			d=1
		p.life=d
		p.save()
	plants = Plant.objects.filter(user=user)
	locate = []
	locate = plant_location(plants,locate)
        return render(request,'sensor/itws.html',{'username':user.username,'plants':plants,'mapdata':locate}) 
    plants = Plant.objects.filter(user=request.user)
    for p in plants:
	d=soilMoisture.objects.filter(pid=p)
	if(len(d)>0):
	     d=int(d[len(d)-1].moisture)
	else:
		d=1
	if(d!=0):
		d=1
	p.life=d
	p.save()
    plants = Plant.objects.filter(user=request.user)
    locate = []
    locate = plant_location(plants,locate)
    return render(request,'sensor/addplant.html',{"form":form,'username':request.user.username,'plants':plants,'mapdata':locate})

@login_required(login_url='/sensor/login_user/')
def modPlant(request):
    form = ModPlant(request.POST or None)
    if request.method=="POST":
        user = request.user
        pid = request.POST['pid']
	lat = request.POST['latitude']
	longi = request.POST['longitude']
        plant=Plant.objects.get(id=pid)
	plant.latitude=lat
	plant.longitude=longi
	plant.save()
        plants = Plant.objects.filter(user=user)
	for p in plants:
		d=soilMoisture.objects.filter(pid=p)
		if(len(d)>0):
			d=int(d[len(d)-1].moisture)
		else:
			d=1
		if(d!=0):
			d=1
		p.life=d
		p.save()
	plants = Plant.objects.filter(user=user)
	locate=[]
	locate = plant_location(plants,locate)
        return render(request,'sensor/itws.html',{'username':user.username,'plants':plants,'mapdata':locate}) 
    plants = Plant.objects.filter(user=request.user)
    for p in plants:
	d=soilMoisture.objects.filter(pid=p)

sensor/templates/sensor/addplant.html
{% extends 'sensor/itws.html' %}

{% block content %}
{% load staticfiles %}
<div class="w3-card">
  <img src="{% static 'sensor/pictures/myplant.jpg' %}" alt="Plant" style="width:30%;height:330px">
  <div class="w3-container">
  <form method="post">
{% csrf_token %}
{% for field in form %}
<label>{{ field.label_tag }}</label>
{{ field }}
{% endfor %}<br>
<button class="w3-button" type="submit" style="background-color:#42aaf4">ADD PLANT</button>
</form>
  </div>
</div>

{% endblock %}

sensor/templates/sensor/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>{% block title %}Plant Nursery: Caretaker of your Plants{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'sensor/css/style.css' %}">
  </head>
  <body background="{% static 'sensor/pictures/wall.jpg' %}">
    <div class="form">
      
      <div class="tab-content">

      <h1>Welcome to Plant Nursery</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'sensor:logout_user' %}">logout</a>
      {% else %}
        <ul class="tab-group">
        <li><a href="{% url 'sensor:register' %}">Sign Up</a></li>
        <li><a href="{% url 'sensor:login_user' %}">Log In</a></li>
      </ul>
      {% endif %}
      <hr>
      <main>
      {% block content %}
      {% endblock %}
    </main>
    </div>
    </div>
    

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{% static 'sensor/js/index.js' %}"></script>

  </body>
</html>

sensor/templates/sensor/basenext.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Django + Charts.js</title>

    {% include 'sensor/css.html' %}
    {% include 'sensor/bootstrap_defaults.html' %}
  </head>
  <body>
    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    {% include 'sensor/js.html' %}
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })
    </script>
  </body>
</html>

sensor/templates/sensor/bootstrap_defaults.html
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

sensor/templates/sensor/charthumid.html
{% extends 'sensor/basenext.html' %}

<script>
{% block jquery %}
var endpoint = "/sensor/{{ pid }}/api/chart1/data"
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)

    }
})



function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2");
    var myChart = new Chart(ctx2, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'Humidity',
            data: defaultData,
            backgroundColor: [
               
                'rgba(153, 102, 255, 0.1)',
                
            ],
            borderColor: [
                
                'rgba(153, 102, 255, 2)',
                
            ],
            borderWidth: 2
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    

    
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}

<div class='row'>
    <div class='col-sm-12' url-endpoint="/sensor/{{ pid }}/api/chart1/data">
        <h1>Humidity</h1>
        
        <div class='col-sm-8'>
            <canvas id="myChart2" width="700" height="500"></canvas>
        </div>


    </div>
</div>

{% endblock content %}

sensor/templates/sensor/chartmoist.html
{% extends 'sensor/basenext.html' %}

<script>
{% block jquery %}
var endpoint = "/sensor/{{ pid }}/api/chart2/data"
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)

    }
})



function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2");
    var myChart = new Chart(ctx2, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'soil Moisture',
            data: defaultData,
            backgroundColor: [
               
                'rgba(45, 175, 95, 0.1)',
                
            ],
            borderColor: [
                
                'rgba(45, 175, 95, 2)',
                
            ],
            borderWidth: 2
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    

    
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}

<div class='row'>
    <div class='col-sm-12' url-endpoint="/sensor/{{ pid }}/api/chart2/data">
        <h1>Soil Moisture</h1>
        
        <div class='col-sm-8'>
            <canvas id="myChart2" width="700" height="500"></canvas>
        </div>


    </div>
</div>

{% endblock content %}

sensor/templates/sensor/charttemp.html
{% extends 'sensor/basenext.html' %}

<script>
{% block jquery %}
var endpoint = '/sensor/{{ pid }}/api/chart/data/'
console.log(endpoint);
var defaultData = [];
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)

    }
})



function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2");
    var myChart = new Chart(ctx2, {
    type: 'line',
    data: {
        labels: labels,
        datasets: [{
            label: 'Temperature',
            data: defaultData,
            backgroundColor: [
               
                'rgba(75, 192, 192, 0.1)',
                
            ],
            borderColor: [
                
                'rgba(75, 192, 192, 2)',
                
            ],
            borderWidth: 2
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    

    
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}

<div class='row'>
    <div class='col-sm-12' url-endpoint="/sensor/{{ pid }}/api/chart/data">
        <h1>Temperature</h1>
        
        <div class='col-sm-8'>
            <canvas id="myChart2" width="700" height="500"></canvas>
        </div>


    </div>
</div>

{% endblock content %}

sensor/templates/sensor/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

sensor/templates/sensor/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, <small>{{ user.username }}</small>!</h2>
  <p>Your email address: {{ user.email }}</p>
{% endblock %}

sensor/templates/sensor/modplant.html
{% extends 'sensor/itws.html' %}

{% block content %}
{% load staticfiles %}
<div class="w3-card">
  <img src="{% static 'sensor/pictures/myplant.jpg' %}" alt="Plant" style="width:30%;height:330px">
  <div class="w3-container">
  <form method="post">
{% csrf_token %}
{% for field in form %}
<label>{{ field.label_tag }}</label>
{{ field }}
{% endfor %}<br>
<button class="w3-button" type="submit" style="background-color:#42aaf4">CHANGE LOCATION</button>
</form>
  </div>
</div>

{% endblock %}

sensor/templates/sensor/signup.html
{% extends 'sensor/base.html' %}

{% block content %}
<div id="signup"> 
  <h1>Sign up</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="field-wrap">
        <label><span class="req">{{ field.label_tag }}</span></label>
        {{ field }}<br>
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="button button-block"/>Get Started</button>
  </form>
</div>
{% endblock %}